### ISSUE TITLE
请问comyui的元数据是以iptc存储的吗

### ISSUE THREAD

**Issue by ggbond5277** [liuqianhonga/ComfyUI-Moments#1]
我不会python，所以我无法理解您的代码，但是我想知道comyui的数据是用什么技术嵌入到图片里的，希望可以告知一下，谢谢

**Comment by liuqianhonga** [comment]
可以去查一下png图片插入长文本信息的资料，

以下是ChatGPT的回答，可以参考下：

在 **ComfyUI** 中，工作流信息被嵌入到 PNG 图像的元数据中，利用的是 PNG 文件的 **tEXt** 或 **iTXt** chunk。这种方式允许在生成的图片中存储附加信息，例如 ComfyUI 的节点参数、生成设置或完整的工作流结构。

以下是 ComfyUI 中插入和读取工作流信息的过程解析：

---

### **插入工作流信息的过程**
1. **生成图片时的元数据写入**：
   - ComfyUI 在生成图片时，会自动将当前的工作流信息序列化为 JSON 格式。
   - 通过 PNG 文件格式的扩展字段（如 `tEXt` 或 `iTXt` chunk）将这段 JSON 数据嵌入。

2. **具体嵌入位置**：
   - 在 PNG 文件中，`tEXt` 或 `iTXt` 块是用于存储键值对的标准区域。
   - ComfyUI 通常会使用一个特定的键（如 `workflow` 或类似字段）来标识这些信息。

3. **如何实现**：
   - 使用 Python 库（如 `Pillow` 或 `pypng`）来操作 PNG 文件并嵌入元数据。
   - 数据通常以压缩形式存储，以减少图片文件的体积。

---

### **读取工作流信息的过程**
1. **从 PNG 提取元数据**：
   - ComfyUI 或其他兼容工具可以读取 PNG 文件中的元数据块。
   - 定位到存储工作流信息的键（如 `workflow`），然后解码 JSON 数据。

2. **应用到工作流中**：
   - 读取到的 JSON 数据会被解析回工作流结构，直接用于恢复 ComfyUI 的工作流设置。

---

### **示例代码**
以下是使用 Python 模拟 ComfyUI 中的元数据插入和读取的过程：

#### 插入工作流信息
```python
from PIL import Image, PngImagePlugin
import json

# 模拟工作流信息
workflow_data = {
    "nodes": [
        {"id": 1, "type": "TextPrompt", "parameters": {"text": "A beautiful landscape"}},
        {"id": 2, "type": "ImageGenerator", "parameters": {"style": "oil painting"}}
    ],
    "connections": [
        {"from": 1, "to": 2}
    ]
}

# 将工作流数据转换为 JSON 字符串
workflow_json = json.dumps(workflow_data)

# 打开 PNG 图像
image = Image.open("example.png")

# 创建 PNG 信息对象
metadata = PngImagePlugin.PngInfo()

# 添加工作流信息
metadata.add_text("workflow", workflow_json)

# 保存带元数据的图片
image.save("example_with_workflow.png", pnginfo=metadata)

print("工作流信息已成功嵌入 PNG 文件！")
```

#### 读取工作流信息
```python
from PIL import PngImagePlugin

# 打开 PNG 图像
image = Image.open("example_with_workflow.png")

# 提取元数据
metadata = image.info

# 读取工作流信息
workflow_json = metadata.get("workflow", None)
if workflow_json:
    workflow_data = json.loads(workflow_json)
    print("提取的工作流信息：", workflow_data)
else:
    print("未找到工作流信息！")
```

---

### **ComfyUI 的具体实现**
在 ComfyUI 的代码中，通常会使用类似上述的方式，但可能会有以下特点：
1. **JSON 格式**：
   - 工作流信息以 JSON 的形式嵌入，便于解析和跨平台使用。

2. **键名**：
   - ComfyUI 中的键名可能是特定的，如 `workflow` 或 `parameters`，用于标识工作流元数据。

3. **压缩和解压**：
   - 为了减少存储占用，工作流数据可能会使用 **zlib** 进行压缩后再存储。

---

### **注意事项**
1. **元数据大小限制**：
   - 虽然 PNG 格式对元数据大小没有严格限制，但过大的元数据会导致文件体积增大。
   - 建议对数据进行压缩处理。

2. **兼容性**：
   - 并非所有查看器或工具都支持读取 PNG 的 `tEXt` 或 `iTXt` 块。
   - 使用特定工具（如 ComfyUI）确保能够正确解析工作流信息。

通过这种方式，ComfyUI 能够将生成图片的详细设置与图片绑定，方便后续的修改和再现。

**Comment by ggbond5277** [comment]
明白了 十分感谢您
